services:
  - type: web
    name: lexagent-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: MONGODB_URL
        value: mongodb+srv://vishaltiwari101999_db_user:vish2323@cluster0.bsi7jvp.mongodb.net/lexagent?retryWrites=true&w=majority
      - key: DATABASE_NAME
        value: lexagent
      - key: SECRET_KEY
        sync: false
